# Generated by Django 3.1 on 2020-11-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Climatic', '0002_remove_usuario_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contador_inicios_fallidos',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Ultimo_inicio_de_sesion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_error',
            field=models.DateField(null=True),
        ),
    ]
